spring.datasource.url=jdbc:postgresql://127.0.0.1:55432/aspiro?sslmode=disable
spring.datasource.username=aspiro
spring.datasource.password=aspiro
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

app.jwt.secret=${JWT_SECRET:MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=}
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000